=== peetdenny/guavatools/XMLTestEngine/schemas/Tests.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.jarden.com/testengine" xmlns:test="http://www.jarden.com/testengine" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	
	<xs:complexType name="Test">
		<xs:sequence>
				<xs:element name="description" type="string" minOccurs="0" maxOccurs="1" />
				<xs:element name="validator"  minOccurs="0" maxOccurs="unbounded" >
					<xs:complexType mixed="false">
						<attribute name="ref" use="optional" type="xs:IDREF" />
					</xs:complexType>
				</xs:element>
		</xs:sequence>
		<attribute name="name" use="required" />
		<attribute name="validator" use="optional" type="xs:IDREF"/>
		<attribute name="inputFile" use="required" />
	</xs:complexType>
	
	<xs:complexType name="Suite">
		<xs:sequence>
			<xs:element name="test" type="test:Test" minOccurs="0" maxOccurs="unbounded" >
				
			</xs:element>
		</xs:sequence>
		<attribute name="name" use="required" />
		<element name="validator">
			<xs:keyref name=""/>
		</element>
			
		</attribute>

	</xs:complexType>
	 

	
	<xs:complexType name="Tests">
		<xs:sequence>
			<xs:element name="test" type="test:Test" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="suite" type="test:Suite" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<attribute name="rootDir" use="required" />
	</xs:complexType>
	
	<xs:complexType name="Validators">
		<xs:sequence>
			<xs:element name="validator" type="test:Validator" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<simpleType name="CheckType">
		<restriction base="xs:string">
			<xs:enumeration value="exists" />
			<xs:enumeration value="not-exists" />
			<xs:enumeration value="equals" />
			<xs:enumeration value="not-equals" />
			<xs:enumeration value="contains" />			
		</restriction>
	</simpleType>
	
	<xs:complexType name="Check" />
				
	<xs:complexType name="Validator">
		<xs:sequence>
			<xs:element name="check" minOccurs="0">
			<xs:complexType mixed="true">
				<xs:attribute name="checkType" type="test:CheckType"/>	
			</xs:complexType>			
			</xs:element>
			<xs:element name="inherit" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType mixed="false">
					<attribute name="ref" use="optional" type="xs:IDREF" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		
	</xs:complexType>
	
	<xs:complexType name="TestConfiguration">
		<xs:sequence>
			<xs:element name="tests" type="test:Tests" />
			<xs:element name="validators" type="test:Validators" />	
		</xs:sequence>
	</xs:complexType>
	
	
	<xs:element name="testConfiguration" type="test:TestConfiguration" />
	
</xs:schema>

=== peetdenny/guavatools/XMLTestEngine/files/Tests.xml
<?xml version="1.0" encoding="UTF-8"?>
<test:testConfiguration xmlns:test="http://www.jarden.com/testengine" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.jarden.com/testengine Tests.xsd ">

  <!-- ###############        TESTS              ###################### -->
  <test:tests rootDir="c:/blahblah">
  
    <test:test name="test1" inputFile="test1.xml"  validator="is-origo-message">
      <test:description>This test is the root test that defines what an origo message is</test:description>
      <test:validator ref="is-origo-message"/>
    </test:test>
    
    
    <test:suite name="origo-suite-one" validator="is-origo-message">
      <test:test name="test1" inputFile="test1.xml"/>	<!-- These 3 tests will all use the same validator defined above -->
      <test:test name="test2" inputFile="test2.xml"/>      
      <test:test name="test3" inputFile="test3.xml"/>
      
      <test:test name="" inputFile="">  
        <test:description>test:description</test:description> 
        <test:validator ref="is-origo-message" />
      </test:test> 
    </test:suite>
  
  
  </test:tests>
  
  
  <!-- ###############       VALIDATORS         ###################### -->
  
  <test:validators>


    <test:validator name="has-mcontrol-node">
	      <test:check checkType="exists">.//m_control</test:check>    
    </test:validator>
    
    <test:validator name="has-product-node">
	      <test:check checkType="exists">.//m_content/application/product</test:check>    
    </test:validator>
    
    <test:validator name="has-minimum-one-risk-benefit">
	      <test:check checkType="exists">.//m_content/application/product</test:check>    
    </test:validator>
    

    <test:validator name="has-mcontent-node">
	      <test:check checkType="exists">.//m_content</test:check>    
    </test:validator>
  
    <test:validator name="is-origo-message">	<!-- this validator inherits the checks from many other validators -->
     	<test:inherit ref="has-mcontrol-node"/>
     	<test:inherit ref="has-mcontent-node"/>     	
     	<test:inherit ref="has-product-node"/>  
     	<test:inherit ref="has-minimum-one-risk-benefit"/>
    </test:validator>
  
    <test:validator name="is-origo-request-message">
      <test:check checkType="exists">.//m_content</test:check>
      <test:inherit ref="is-origo-message"/>
    </test:validator>
  
    <test:validator name="has-variations">
      <test:check checkType="not-exists">.//m_content</test:check>
    </test:validator>
  
  
  </test:validators>
  
  
  
  
</test:testConfiguration>
